import { ApplicationConfig, ServerConfig } from '../types';

/**
 * DO NOT EDIT THIS FILE!
 * USE THIS FILE AS A TEMPLATE FOR local.ts FOR LOCAL CONFIG OVERRIDES
 */

/**
 * This config will be applied for client- and server-side application
 */
const commonApplicationConfig: Partial<ApplicationConfig> = {};

/**
 * This config will be applied for the client-side application only
 */
const clientApplicationConfig: Partial<ApplicationConfig> = {};

/**
 * This config will be applied for the server-side application only
 */
const serverApplicationConfig: Partial<ApplicationConfig> = {};

/**
 * This config will be applied for a server which serves the application
 */
const serverConfig: Partial<ServerConfig> = {};

export default {
  clientApplicationConfig: {
    ...commonApplicationConfig,
    ...clientApplicationConfig,
  },
  serverApplicationConfig: {
    ...commonApplicationConfig,
    ...serverApplicationConfig,
  },
  serverConfig,
};
