export const SIGNAL_ACTION = 'INTERNAL/ACTION_SIGNAL';
export const SEQUENCE_ACTION = 'INTERNAL/ACTION_SEQUENCE';
export const PARALLEL_ACTION = 'INTERNAL/ACTION_PARALLEL';
export const WITH_SELECTORS_ACTION = 'INTERNAL/ACTION_WITH_SELECTORS';
export const NOOP_ACTION = 'INTERNAL/ACTION_NOOP';
